### ISSUE TITLE
Implémenter le chat

### ISSUE THREAD

**Issue by kuasar-mknd** [C-Super/couleur3#20]

**Comment by Daniel-Mendes** [comment]
Liens utiles:

https://pusher.com/
https://www.cloudways.com/blog/realtime-chatroom-with-laravel-vuejs-pusher/

**Comment by Daniel-Mendes** [comment]
https://github.com/maitrungduc1410/public-channel-realtime-chat

https://medium.com/@antoine.lame/using-soketi-with-laravel-902ee1e6b7b
