### ISSUE TITLE
Implémenter l'authentification auditeur

### ISSUE THREAD

**Issue by Daniel-Mendes** [C-Super/couleur3#74]
On peut utiliser [Laravel Breeze](https://laravel.com/docs/10.x/starter-kits#breeze-and-inertia) avec l'option Vue & Inertia. C'est une solution simple.
ou bien le nouveau package [Laravel Jetstream](https://jetstream.laravel.com/3.x/introduction.html#inertia-vue) avec l'option Vue & Inertia,c'est plus compliqué mais plus complet  gère la double authentification, team management.

C'est deux solutions permettent de créer les pages de login, d'enregistrement, mot de passe oublié, etc..

**Comment by kuasar-mknd** [comment]
On utilise breeze
